support the `:has` selector for checking descendants
Connexions/cssselect2 pull request #5
Opened 2016-10-20 00:41 UTC by philschatz

Allows for selector fanciness like `.exercise:has(.solution)` (from [sizzle](https://sizzlejs.com/)) rather than having to encode temporary data into the DOM via multiple passes (ie [cnx-recipes#85](https://github.com/Connexions/cnx-recipes/pull/85/files#diff-5503849fa0b906e2868f1793f3f36daaR6) ).

Currently, this is sprinkled around in [multiple passes](https://github.com/Connexions/cnx-recipes/blob/master/books/rulesets/common/_utils.scss#L47-L69) (is very confusing to know where this is used) and an additional `os-hasSolutions` class is added to exercises. There are probably other places where this would be useful 😄 

Occurrences that could be removed if this is added: [search results for hasSolutions](https://github.com/Connexions/cnx-recipes/search?utf8=%E2%9C%93&q=hasSolutions)

/cc @helenemccarron @reedstrm

2016-10-20 14:09 UTC, reedstrm requested changes
I agree this is very tight code to work in: normally `eval()` throws all sorts of red flags, but I think that design may be why this solution is so much faster than the previous xpath based one. 

Having said that, `:has()` is in the current editors draft of CSS-selectors-4. It is not in the currently published version (from 2013). I want to keep core cssselect2 standards compliant, that's why I wrote the `extensions` mechanism in there. It seems to me that `:match()` and `:has()` should have the same logical needs: could you rewrite this to use `extensions`?

2016-10-20 14:10 UTC, reedstrm commented
BTW, if `extensions` is not sufficient, I'll help extend it :-)

2016-10-20 14:24 UTC, reedstrm commented
take a look at fd2aba6ea03aed8e4f8b5fb02c71f9e00f60d4b2

2016-10-20 17:36 UTC, philschatz commented
I initially tried implementing it as an extension but ran into the problem of having to parse the arguments of `:has` into an AST. The code that tipped me over from doing it as an extension is the changes in [parser.py](https://github.com/Connexions/cssselect2/pull/5/files#diff-877bf271692396d206564db47990da76R163) . If you know of a way to do that I'm all 👂 's ; )

2016-10-28 21:50 UTC, reedstrm commented
We discussed this directly a bit, I'll take a look at how it's being parsed, perhaps we need to add an extension hook in the parsing as well.

2016-12-03 02:40 UTC, philschatz commented
ping 😄  . I ran into wanting this feature for figures/tables and checking if they have a caption/title to decide how to change the markup in https://github.com/Connexions/cnx-recipes/pull/112

2017-05-10 20:21 UTC, pumazi commented
What's keeping this from being merged?

2019-02-20 20:38 UTC, brittweinstein commented
@pumazi is this linked to any issue? can we close this?

2019-02-22 20:49 UTC, brittweinstein commented
CLOSING. If this presents itself as an issue again, we will reopen.

2019-02-22 20:49 UTC, closed without merging